server:
  port: 9191
  
spring:
  application:
    name: ARIOS-GATEWAY
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
           allowedOrigins: "*"
           allowedMethods: "*"
           allowedHeaders: "*"
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
      - id: APPLICATION-SERVICE
        uri: lb://APPLICATION-SERVICE
        predicates:
        - Path=/application/**
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost